<?php

namespace ContainerWERoRC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFaviconControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FaviconController' shared autowired service.
     *
     * @return \App\Controller\FaviconController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['App\\Controller\\FaviconController'] = new \App\Controller\FaviconController();
    }
}
