<?php

namespace ContainerWERoRC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashRecoveryCodesCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\HashRecoveryCodesCommand' shared autowired service.
     *
     * @return \App\Command\HashRecoveryCodesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\HashRecoveryCodesCommand'] = $instance = new \App\Command\HashRecoveryCodesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Service\RecoveryCodeHasher());

        $instance->setName('app:migrate:hash-recovery-codes');
        $instance->setDescription('Migra los recovery codes existentes a formato hasheado con Argon2ID');

        return $instance;
    }
}
