<?php

namespace ContainerWERoRC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashRecoveryCodesCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\HashRecoveryCodesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\HashRecoveryCodesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:migrate:hash-recovery-codes', [], 'Migra los recovery codes existentes a formato hasheado con Argon2ID', false, #[\Closure(name: 'App\\Command\\HashRecoveryCodesCommand')] fn (): \App\Command\HashRecoveryCodesCommand => ($container->privates['App\\Command\\HashRecoveryCodesCommand'] ?? $container->load('getHashRecoveryCodesCommandService')));
    }
}
