<?php

namespace ContainerWERoRC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordStrengthValidatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Validator\Constraints\PasswordStrengthValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\PasswordStrengthValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\Constraints\\PasswordStrengthValidator'] = new \App\Validator\Constraints\PasswordStrengthValidator();
    }
}
