<?php

namespace ContainerWERoRC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_RememberMeHandler_MainService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authenticator.remember_me_handler.main' shared service.
     *
     * @return \Symfony\Component\Security\Http\RememberMe\SignatureRememberMeHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Security\\UserProvider'] ?? $container->load('getUserProviderService'));

        if (isset($container->privates['security.authenticator.remember_me_handler.main'])) {
            return $container->privates['security.authenticator.remember_me_handler.main'];
        }

        $instance = new \Symfony\Component\Security\Http\RememberMe\SignatureRememberMeHandler(new \Symfony\Component\Security\Core\Signature\SignatureHasher(($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), ['password'], $container->getEnv('APP_SECRET'), NULL, NULL), $a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ['secret' => $container->getEnv('APP_SECRET'), 'lifetime' => 604800, 'path' => '/', 'always_remember_me' => false, 'user_providers' => [], 'catch_exceptions' => true, 'signature_properties' => ['password'], 'name' => 'REMEMBERME', 'domain' => NULL, 'secure' => NULL, 'httponly' => true, 'samesite' => 'lax', 'remember_me_parameter' => '_remember_me'], ($container->services['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)));

        if (isset($container->privates['security.authenticator.remember_me_handler.main'])) {
            return $container->privates['security.authenticator.remember_me_handler.main'];
        }

        return $container->privates['security.authenticator.remember_me_handler.main'] = $instance;
    }
}
