<?php

namespace ContainerWERoRC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecuritySettingsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SecuritySettingsController' shared autowired service.
     *
     * @return \App\Controller\SecuritySettingsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));
        $b = ($container->privates['App\\Service\\SecurityLogger'] ?? $container->load('getSecurityLoggerService'));

        $container->services['App\\Controller\\SecuritySettingsController'] = $instance = new \App\Controller\SecuritySettingsController($a, new \App\Service\TwoFactorAuthService($a, new \PragmaRX\Google2FA\Google2FA(), $b), $b);

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\SecuritySettingsController', $container));

        return $instance;
    }
}
