<?php

namespace ContainerWERoRC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SystemController' shared autowired service.
     *
     * @return \App\Controller\SystemController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SystemController'] = $instance = new \App\Controller\SystemController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\SystemController', $container));

        return $instance;
    }
}
