<?php

namespace ContainerWERoRC8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\UserProvider' shared autowired service.
     *
     * @return \App\Security\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Security\\UserProvider'])) {
            return $container->privates['App\\Security\\UserProvider'];
        }

        $instance = new \App\Security\UserProvider($a);

        if (isset($container->privates['App\\Security\\UserProvider'])) {
            return $container->privates['App\\Security\\UserProvider'];
        }

        return $container->privates['App\\Security\\UserProvider'] = $instance;
    }
}
