<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAKx5jdw\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAKx5jdw/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAKx5jdw.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAKx5jdw\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAKx5jdw\App_KernelProdContainer([
    'container.build_hash' => 'AKx5jdw',
    'container.build_id' => '5fced1b5',
    'container.build_time' => 1775857674,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAKx5jdw');
