<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWERoRC8\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWERoRC8/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWERoRC8.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWERoRC8\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWERoRC8\App_KernelProdContainer([
    'container.build_hash' => 'WERoRC8',
    'container.build_id' => 'a9bd4ff0',
    'container.build_time' => 1773766819,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWERoRC8');
