<?php

namespace Container8wDYeBQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncryptTotpSecretsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\EncryptTotpSecretsCommand' shared autowired service.
     *
     * @return \App\Command\EncryptTotpSecretsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/EncryptTotpSecretsCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/EncryptionService.php';

        $container->privates['App\\Command\\EncryptTotpSecretsCommand'] = $instance = new \App\Command\EncryptTotpSecretsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Service\EncryptionService($container->getEnv('APP_SECRET')));

        $instance->setName('app:migrate:encrypt-totp');
        $instance->setDescription('Migra los TOTP secrets existentes a formato encriptado');

        return $instance;
    }
}
