<?php

namespace Container8wDYeBQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFaviconControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FaviconController' shared autowired service.
     *
     * @return \App\Controller\FaviconController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/FaviconController.php';

        return $container->services['App\\Controller\\FaviconController'] = new \App\Controller\FaviconController();
    }
}
