<?php

namespace Container8wDYeBQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashRecoveryCodesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\HashRecoveryCodesCommand' shared autowired service.
     *
     * @return \App\Command\HashRecoveryCodesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/HashRecoveryCodesCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RecoveryCodeHasher.php';

        $container->privates['App\\Command\\HashRecoveryCodesCommand'] = $instance = new \App\Command\HashRecoveryCodesCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \App\Service\RecoveryCodeHasher());

        $instance->setName('app:migrate:hash-recovery-codes');
        $instance->setDescription('Migra los recovery codes existentes a formato hasheado con Argon2ID');

        return $instance;
    }
}
