<?php

namespace Container8wDYeBQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevitAPIControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\API\RevitAPIController' shared autowired service.
     *
     * @return \App\Controller\API\RevitAPIController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/API/RevitAPIController.php';

        $container->services['App\\Controller\\API\\RevitAPIController'] = $instance = new \App\Controller\API\RevitAPIController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), $container->getEnv('JWT_SECRET_KEY'));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\API\\RevitAPIController', $container));

        return $instance;
    }
}
