<?php

namespace Container8wDYeBQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SecurityController' shared autowired service.
     *
     * @return \App\Controller\SecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SecurityController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RateLimitingService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));
        $b = ($container->privates['App\\Service\\SecurityLogger'] ?? $container->load('getSecurityLoggerService'));

        $container->services['App\\Controller\\SecurityController'] = $instance = new \App\Controller\SecurityController($a, $b, new \App\Service\RateLimitingService($a, $b, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\SecurityController', $container));

        return $instance;
    }
}
