<?php

namespace Container8wDYeBQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestEmailCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestEmailCommand' shared autowired service.
     *
     * @return \App\Command\TestEmailCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TestEmailCommand.php';

        $container->privates['App\\Command\\TestEmailCommand'] = $instance = new \App\Command\TestEmailCommand(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));

        $instance->setName('app:test-email');
        $instance->setDescription('Envía un correo de prueba a Mailpit');

        return $instance;
    }
}
