<?php

namespace ContainerDOmJQ3A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncryptTotpSecretsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\EncryptTotpSecretsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\EncryptTotpSecretsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:migrate:encrypt-totp', [], 'Migra los TOTP secrets existentes a formato encriptado', false, #[\Closure(name: 'App\\Command\\EncryptTotpSecretsCommand')] fn (): \App\Command\EncryptTotpSecretsCommand => ($container->privates['App\\Command\\EncryptTotpSecretsCommand'] ?? $container->load('getEncryptTotpSecretsCommandService')));
    }
}
