<?php

namespace ContainerDOmJQ3A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordResetControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PasswordResetController' shared autowired service.
     *
     * @return \App\Controller\PasswordResetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PasswordResetController.php';

        $container->services['App\\Controller\\PasswordResetController'] = $instance = new \App\Controller\PasswordResetController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['App\\Service\\SecurityLogger'] ?? $container->load('getSecurityLoggerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\PasswordResetController', $container));

        return $instance;
    }
}
