<?php

namespace ContainerDOmJQ3A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityLoggerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SecurityLogger' shared autowired service.
     *
     * @return \App\Service\SecurityLogger
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SecurityLogger.php';

        return $container->privates['App\\Service\\SecurityLogger'] = new \App\Service\SecurityLogger(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
