<?php

namespace ContainerDOmJQ3A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestEmailCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TestEmailCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\TestEmailCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:test-email', [], 'Envía un correo de prueba a Mailpit', false, #[\Closure(name: 'App\\Command\\TestEmailCommand')] fn (): \App\Command\TestEmailCommand => ($container->privates['App\\Command\\TestEmailCommand'] ?? $container->load('getTestEmailCommandService')));
    }
}
