<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDOmJQ3A\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDOmJQ3A/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDOmJQ3A.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDOmJQ3A\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDOmJQ3A\App_KernelDevDebugContainer([
    'container.build_hash' => 'DOmJQ3A',
    'container.build_id' => 'b948c7ed',
    'container.build_time' => 1774017794,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDOmJQ3A');
