<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDfFwmcn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDfFwmcn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDfFwmcn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDfFwmcn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDfFwmcn\App_KernelDevDebugContainer([
    'container.build_hash' => 'DfFwmcn',
    'container.build_id' => '803e49fe',
    'container.build_time' => 1776276799,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDfFwmcn');
