<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNBrsPQK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNBrsPQK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNBrsPQK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNBrsPQK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNBrsPQK\App_KernelDevDebugContainer([
    'container.build_hash' => 'NBrsPQK',
    'container.build_id' => '3c77cffc',
    'container.build_time' => 1775592218,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNBrsPQK');
