<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proyecto extends \App\Entity\Proyecto implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cliente' => [parent::class, 'cliente', null, 16],
        "\0".parent::class."\0".'codigo' => [parent::class, 'codigo', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null, 16],
        "\0".parent::class."\0".'estado' => [parent::class, 'estado', null, 16],
        "\0".parent::class."\0".'fechaFin' => [parent::class, 'fechaFin', null, 16],
        "\0".parent::class."\0".'fechaInicio' => [parent::class, 'fechaInicio', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null, 16],
        "\0".parent::class."\0".'presupuestoTotal' => [parent::class, 'presupuestoTotal', null, 16],
        "\0".parent::class."\0".'tenant' => [parent::class, 'tenant', null, 16],
        "\0".parent::class."\0".'ubicacion' => [parent::class, 'ubicacion', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'cliente' => [parent::class, 'cliente', null, 16],
        'codigo' => [parent::class, 'codigo', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'descripcion' => [parent::class, 'descripcion', null, 16],
        'estado' => [parent::class, 'estado', null, 16],
        'fechaFin' => [parent::class, 'fechaFin', null, 16],
        'fechaInicio' => [parent::class, 'fechaInicio', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nombre' => [parent::class, 'nombre', null, 16],
        'presupuestoTotal' => [parent::class, 'presupuestoTotal', null, 16],
        'tenant' => [parent::class, 'tenant', null, 16],
        'ubicacion' => [parent::class, 'ubicacion', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
