<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'emailVerifiedAt' => [parent::class, 'emailVerifiedAt', null, 16],
        "\0".parent::class."\0".'failedLoginAttempts' => [parent::class, 'failedLoginAttempts', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        "\0".parent::class."\0".'lastLoginIp' => [parent::class, 'lastLoginIp', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'locale' => [parent::class, 'locale', null, 16],
        "\0".parent::class."\0".'lockedUntil' => [parent::class, 'lockedUntil', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'passwordChangedAt' => [parent::class, 'passwordChangedAt', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'requirePasswordChange' => [parent::class, 'requirePasswordChange', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'tenant' => [parent::class, 'tenant', null, 16],
        "\0".parent::class."\0".'themeMode' => [parent::class, 'themeMode', null, 16],
        "\0".parent::class."\0".'themePrimaryColor' => [parent::class, 'themePrimaryColor', null, 16],
        "\0".parent::class."\0".'themeSecondaryColor' => [parent::class, 'themeSecondaryColor', null, 16],
        "\0".parent::class."\0".'timezone' => [parent::class, 'timezone', null, 16],
        "\0".parent::class."\0".'totpEnabled' => [parent::class, 'totpEnabled', null, 16],
        "\0".parent::class."\0".'totpSecret' => [parent::class, 'totpSecret', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        "\0".parent::class."\0".'webauthnEnabled' => [parent::class, 'webauthnEnabled', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'emailVerifiedAt' => [parent::class, 'emailVerifiedAt', null, 16],
        'failedLoginAttempts' => [parent::class, 'failedLoginAttempts', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        'lastLoginIp' => [parent::class, 'lastLoginIp', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'locale' => [parent::class, 'locale', null, 16],
        'lockedUntil' => [parent::class, 'lockedUntil', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'passwordChangedAt' => [parent::class, 'passwordChangedAt', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'requirePasswordChange' => [parent::class, 'requirePasswordChange', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'tenant' => [parent::class, 'tenant', null, 16],
        'themeMode' => [parent::class, 'themeMode', null, 16],
        'themePrimaryColor' => [parent::class, 'themePrimaryColor', null, 16],
        'themeSecondaryColor' => [parent::class, 'themeSecondaryColor', null, 16],
        'timezone' => [parent::class, 'timezone', null, 16],
        'totpEnabled' => [parent::class, 'totpEnabled', null, 16],
        'totpSecret' => [parent::class, 'totpSecret', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'username' => [parent::class, 'username', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
        'webauthnEnabled' => [parent::class, 'webauthnEnabled', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
