<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class APULabor extends \App\Entity\APULabor implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'apuItem' => [parent::class, 'apuItem', null, 16],
        "\0".parent::class."\0".'cHora' => [parent::class, 'cHora', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'jorHora' => [parent::class, 'jorHora', null, 16],
        "\0".parent::class."\0".'numero' => [parent::class, 'numero', null, 16],
        'apuItem' => [parent::class, 'apuItem', null, 16],
        'cHora' => [parent::class, 'cHora', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'descripcion' => [parent::class, 'descripcion', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'jorHora' => [parent::class, 'jorHora', null, 16],
        'numero' => [parent::class, 'numero', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
