<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RevitFile extends \App\Entity\RevitFile implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'errorMessage' => [parent::class, 'errorMessage', null, 16],
        "\0".parent::class."\0".'fileHash' => [parent::class, 'fileHash', null, 16],
        "\0".parent::class."\0".'filePath' => [parent::class, 'filePath', null, 16],
        "\0".parent::class."\0".'fileSize' => [parent::class, 'fileSize', null, 16],
        "\0".parent::class."\0".'fileType' => [parent::class, 'fileType', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'originalFilename' => [parent::class, 'originalFilename', null, 16],
        "\0".parent::class."\0".'processedAt' => [parent::class, 'processedAt', null, 16],
        "\0".parent::class."\0".'processingResult' => [parent::class, 'processingResult', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'storedFilename' => [parent::class, 'storedFilename', null, 16],
        "\0".parent::class."\0".'tenant' => [parent::class, 'tenant', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'uploadedAt' => [parent::class, 'uploadedAt', null, 16],
        "\0".parent::class."\0".'uploadedBy' => [parent::class, 'uploadedBy', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'errorMessage' => [parent::class, 'errorMessage', null, 16],
        'fileHash' => [parent::class, 'fileHash', null, 16],
        'filePath' => [parent::class, 'filePath', null, 16],
        'fileSize' => [parent::class, 'fileSize', null, 16],
        'fileType' => [parent::class, 'fileType', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'originalFilename' => [parent::class, 'originalFilename', null, 16],
        'processedAt' => [parent::class, 'processedAt', null, 16],
        'processingResult' => [parent::class, 'processingResult', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'storedFilename' => [parent::class, 'storedFilename', null, 16],
        'tenant' => [parent::class, 'tenant', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'uploadedAt' => [parent::class, 'uploadedAt', null, 16],
        'uploadedBy' => [parent::class, 'uploadedBy', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
