<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tenant extends \App\Entity\Tenant implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'domain' => [parent::class, 'domain', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'logoUrl' => [parent::class, 'logoUrl', null, 16],
        "\0".parent::class."\0".'maxProjects' => [parent::class, 'maxProjects', null, 16],
        "\0".parent::class."\0".'maxUsers' => [parent::class, 'maxUsers', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'plan' => [parent::class, 'plan', null, 16],
        "\0".parent::class."\0".'planAutoRenew' => [parent::class, 'planAutoRenew', null, 16],
        "\0".parent::class."\0".'planExpiresAt' => [parent::class, 'planExpiresAt', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'themeMode' => [parent::class, 'themeMode', null, 16],
        "\0".parent::class."\0".'themePrimaryColor' => [parent::class, 'themePrimaryColor', null, 16],
        "\0".parent::class."\0".'themeSecondaryColor' => [parent::class, 'themeSecondaryColor', null, 16],
        "\0".parent::class."\0".'timezone' => [parent::class, 'timezone', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'domain' => [parent::class, 'domain', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'logoUrl' => [parent::class, 'logoUrl', null, 16],
        'maxProjects' => [parent::class, 'maxProjects', null, 16],
        'maxUsers' => [parent::class, 'maxUsers', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'plan' => [parent::class, 'plan', null, 16],
        'planAutoRenew' => [parent::class, 'planAutoRenew', null, 16],
        'planExpiresAt' => [parent::class, 'planExpiresAt', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'themeMode' => [parent::class, 'themeMode', null, 16],
        'themePrimaryColor' => [parent::class, 'themePrimaryColor', null, 16],
        'themeSecondaryColor' => [parent::class, 'themeSecondaryColor', null, 16],
        'timezone' => [parent::class, 'timezone', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'users' => [parent::class, 'users', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
