<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Apu extends \App\Entity\Apu implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cantidad' => [parent::class, 'cantidad', null, 16],
        "\0".parent::class."\0".'codigo' => [parent::class, 'codigo', null, 16],
        "\0".parent::class."\0".'costoTotal' => [parent::class, 'costoTotal', null, 16],
        "\0".parent::class."\0".'costoUnitario' => [parent::class, 'costoUnitario', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'proyecto' => [parent::class, 'proyecto', null, 16],
        "\0".parent::class."\0".'rendimiento' => [parent::class, 'rendimiento', null, 16],
        "\0".parent::class."\0".'tenant' => [parent::class, 'tenant', null, 16],
        "\0".parent::class."\0".'unidad' => [parent::class, 'unidad', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'cantidad' => [parent::class, 'cantidad', null, 16],
        'codigo' => [parent::class, 'codigo', null, 16],
        'costoTotal' => [parent::class, 'costoTotal', null, 16],
        'costoUnitario' => [parent::class, 'costoUnitario', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'descripcion' => [parent::class, 'descripcion', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'proyecto' => [parent::class, 'proyecto', null, 16],
        'rendimiento' => [parent::class, 'rendimiento', null, 16],
        'tenant' => [parent::class, 'tenant', null, 16],
        'unidad' => [parent::class, 'unidad', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
