<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LoginSession extends \App\Entity\LoginSession implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'expiresAt' => [parent::class, 'expiresAt', null, 16],
        "\0".parent::class."\0".'fingerprint' => [parent::class, 'fingerprint', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'ipAddress' => [parent::class, 'ipAddress', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'lastActivityAt' => [parent::class, 'lastActivityAt', null, 16],
        "\0".parent::class."\0".'sessionId' => [parent::class, 'sessionId', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        "\0".parent::class."\0".'userAgent' => [parent::class, 'userAgent', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'expiresAt' => [parent::class, 'expiresAt', null, 16],
        'fingerprint' => [parent::class, 'fingerprint', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'ipAddress' => [parent::class, 'ipAddress', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'lastActivityAt' => [parent::class, 'lastActivityAt', null, 16],
        'sessionId' => [parent::class, 'sessionId', null, 16],
        'user' => [parent::class, 'user', null, 16],
        'userAgent' => [parent::class, 'userAgent', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
