<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BlockedIp extends \App\Entity\BlockedIp implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'blockedBy' => [parent::class, 'blockedBy', null, 16],
        "\0".parent::class."\0".'blockedUntil' => [parent::class, 'blockedUntil', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'ipAddress' => [parent::class, 'ipAddress', null, 16],
        "\0".parent::class."\0".'reason' => [parent::class, 'reason', null, 16],
        "\0".parent::class."\0".'riskScore' => [parent::class, 'riskScore', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'blockedBy' => [parent::class, 'blockedBy', null, 16],
        'blockedUntil' => [parent::class, 'blockedUntil', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'ipAddress' => [parent::class, 'ipAddress', null, 16],
        'reason' => [parent::class, 'reason', null, 16],
        'riskScore' => [parent::class, 'riskScore', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
