<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class APUItem extends \App\Entity\APUItem implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'equipment' => [parent::class, 'equipment', null, 16],
        "\0".parent::class."\0".'equipmentCost' => [parent::class, 'equipmentCost', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'khu' => [parent::class, 'khu', null, 16],
        "\0".parent::class."\0".'labor' => [parent::class, 'labor', null, 16],
        "\0".parent::class."\0".'laborCost' => [parent::class, 'laborCost', null, 16],
        "\0".parent::class."\0".'materialCost' => [parent::class, 'materialCost', null, 16],
        "\0".parent::class."\0".'materials' => [parent::class, 'materials', null, 16],
        "\0".parent::class."\0".'rendimientoUh' => [parent::class, 'rendimientoUh', null, 16],
        "\0".parent::class."\0".'tenant' => [parent::class, 'tenant', null, 16],
        "\0".parent::class."\0".'totalCost' => [parent::class, 'totalCost', null, 16],
        "\0".parent::class."\0".'transport' => [parent::class, 'transport', null, 16],
        "\0".parent::class."\0".'transportCost' => [parent::class, 'transportCost', null, 16],
        "\0".parent::class."\0".'unit' => [parent::class, 'unit', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'equipment' => [parent::class, 'equipment', null, 16],
        'equipmentCost' => [parent::class, 'equipmentCost', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'khu' => [parent::class, 'khu', null, 16],
        'labor' => [parent::class, 'labor', null, 16],
        'laborCost' => [parent::class, 'laborCost', null, 16],
        'materialCost' => [parent::class, 'materialCost', null, 16],
        'materials' => [parent::class, 'materials', null, 16],
        'rendimientoUh' => [parent::class, 'rendimientoUh', null, 16],
        'tenant' => [parent::class, 'tenant', null, 16],
        'totalCost' => [parent::class, 'totalCost', null, 16],
        'transport' => [parent::class, 'transport', null, 16],
        'transportCost' => [parent::class, 'transportCost', null, 16],
        'unit' => [parent::class, 'unit', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'uuid' => [parent::class, 'uuid', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
